### ISSUE TITLE
wait_for_arrival error

### ISSUE THREAD

**Issue by levthedev** [OpenTrons/opentrons-api#61]
I am getting this error when I do a move_to on a smoothie (mine is not connected to a robot but that shouldn't make a difference for jogging). I also get it occasionally on the Virtual Smoothie when doing a move_to.

```Traceback (most recent call last):
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/levkravinsky/Desktop/ot/v2/server/main.py", line 258, in jog
    result = robot.move_head(mode="relative", **coords)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/opentrons_sdk/robot/robot.py", line 209, in move_head
    self._driver.move_head(*args, **kwargs)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/opentrons_sdk/drivers/motor.py", line 315, in move_head
    return self.consume_move_commands(args_list, increment)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/opentrons_sdk/drivers/motor.py", line 330, in consume_move_commands
    self.wait_for_arrival(tolerance)
  File "/Users/levkravinsky/Desktop/ot/v2/server/env/lib/python3.4/site-packages/opentrons_sdk/drivers/motor.py", line 354, in wait_for_arrival
    dist = pow(diff['x'], 2) + pow(diff['y'], 2) + pow(diff['z'], 2)
KeyError: 'x'```

**Comment by levthedev** [comment]
Fixed - this was due to a frontend bug with the Socketio thread asking the backend for the current position in the middle of other commands (getting current position is not thread-safe).
